apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
data:
  DATABASE: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "fastfood-db.cs34oe66a9rt.us-east-1.rds.amazonaws.com"
  AUTH_SERVICE_URL: "https://06vrwdm931.execute-api.us-east-1.amazonaws.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
type: Opaque
data:
  DATABASE_USER: "ZmFzdGZvb2Q="  # Base64 encoded "fastfood"
  DATABASE_PASSWORD: "VGVzdGUxMjM="  # Base64 encoded "Teste123"
